---
apiVersion: v1
kind: Pod
metadata:
  name: sample-s3-1
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: s3sidecar
    image: quay.io/jclaret/s3image-fedora
    command: ["/bin/sh", "-c"]
    args:
      - |
        exec s3fs $BUCKET $MOUNTPOINT $FUSE_OPTS -o url=$S3URL -o use_cache=/tmp -f
    imagePullPolicy: Always
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
    env:
      - name: FUSE_OPTS
        value: "-o use_path_request_style -o no_check_certificate"
      - name: S3URL
        value: https://s3-openshift-storage.apps.mno.5g-deployment.lab
      - name: AWSACCESSKEYID
        value: "8t1FA7FtnhtgIqnyefix"
      - name: AWSSECRETACCESSKEY
        value: "xOS4g+3oIBTR8irjsFiV+frOi/vmvFVud//1vY26"
      - name: BUCKET
        value: s3-testing-63ad0329-c74b-42be-83c5-21a6d3914c30
      - name: MOUNTPOINT
        value: "/test"
    volumeMounts:
    - name: shared-data
      mountPath: /test
      mountPropagation: Bidirectional
  - name: debian-container
    image: quay.io/jclaret/s3image-fedora
    volumeMounts:
    - name: shared-data
      mountPath: /test
      mountPropagation: HostToContainer
